server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/meocms?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        tomcat:
            test-while-idle: true
            validation-query: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
#    freemarker:
meo:
    company-name: MeoCMS